# Generated by Django 6.0.1 on 2026-01-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='sermon',
            name='youtube_id',
            field=models.CharField(default='-', help_text='Solo el ID del video (ej: dQw4w9WgXcQ)', max_length=20),
            preserve_default=False,
        ),
    ]
