# Generated by Django 6.0.1 on 2026-01-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_remove_sermon_youtube_url_sermon_youtube_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='sermon',
            name='youtube_url',
            field=models.URLField(default='_'),
            preserve_default=False,
        ),
    ]
