# Generated by Django 6.0.1 on 2026-01-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reflection',
        ),
    ]
