# Generated by Django 6.0.1 on 2026-01-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='content',
            field=models.TextField(verbose_name='Reflection text'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='created',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatically generated from the title', unique=True),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
