# Generated by Django 6.0.1 on 2026-01-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0002_alter_reflection_content_alter_reflection_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='scripture',
            field=models.TextField(default='Texto bíblico pendiente', help_text='Ejemplo: Salmo 23:1–4 o el texto completo', verbose_name='Texto bíblico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reflection',
            name='content',
            field=models.TextField(verbose_name='Cuerpo de la Reflexión'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automáticamente generado a partir del título.', unique=True),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
