# Generated by Django 6.0.1 on 2026-01-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0003_reflection_scripture_alter_reflection_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
